### ISSUE TITLE
Can we set the target of the Bubble Popup to the navigation bar?

### ISSUE THREAD

**Issue by eyacoub** [baskren/Forms9PatchDemo#4]

**Comment by baskren** [comment]
BubblePopup uses the location of a VisualElement to calculate where it will point.  Navigation bar buttons are not derived from VisualElement (they're derived from Element) and so they so not provide the information BubblePopup needs.

I've looked into if there would be a way to work around this and, because of how the Platform renderers are constructed,  I found this to be not worth the effort.
